using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class TextLoader : MonoBehaviour
{

    public int names;
    public int log;
    public int yes;
    public int no;

    // Start is called before the first frame update
    void Start()
    {
        
    }

    // Update is called once per frame
    void Update()
    {
        
    }

    public void Work() {
        Texts.instance.GetText(names,log,yes);
    

    }
    public void Work2()
    {
        Texts.instance.GetText2(names,log,yes,no);
    }

   
    public virtual void SpecialWorkyes() {

    }
    public virtual void SpecialWorkno()
    {

    }
}
